name: Build and Run

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-run:
    name: Build and run with startup msg verification
    uses: arielswalker/cFS/.github/workflows/build-run-app.yml@arielswalker-test-sch
    with:
      startup-string: Application initialized
